import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "sonner";
import { Suspense } from "react";
import ReduxProvider from "@/redux/Provider";
import Loading from "@/components/Others/Loader/Loading";
import {
  antic,
  bitcount,
  gravitas,
  lobster,
  openSans,
  playfair,
  roboto,
  rowdies,
} from "@/fonts/Fonts";
import { CustomThemeProvider } from "@/components/Provider/ThemeProvider";

export const metadata: Metadata = {
  title: "Rakib Utsho",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${openSans.variable} ${playfair.variable} ${bitcount.variable} ${lobster.variable} ${roboto.variable} ${gravitas.variable} ${rowdies.variable} ${antic.variable} antialiased`}
        suppressHydrationWarning
      >
        <Suspense fallback={<Loading />}>
          <CustomThemeProvider
            attribute="class"
            defaultTheme="light"
            enableSystem
          >
            <ReduxProvider>
              {children}
              <Toaster richColors position="top-right" />
            </ReduxProvider>
          </CustomThemeProvider>
        </Suspense>
      </body>
    </html>
  );
}
